### **1. Print "+"**

**Description:**
Given a single positive odd integer 'n' greater than 2, create a NumPy array of size (n x n) with all zeros and ones such that the ones make a shape like '+'. The lines of the plus must be present at the middle row and column.
Hint: Start by creating a (n x n) array with all zeroes using the np.zeros() function and then fill in the ones at the appropriate indices. Use integer division (//) to access the middle rows and columns

**Examples:**
Input 1:
3
Output 1:

```
[[0 1 0]
 [1 1 1]
 [0 1 0]]
```

Input 2:
5
Output 1:

```
[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]
```

**Explanation:** Notice that the 1s in the arrays make a shape like '+'.


In [4]:
import numpy as np
import pandas as pd

In [2]:
# Write your code here

# Get input value of n
n = int(input("Enter a positive odd integer greater than 2: "))

# Create an (n x n) array of zeros
arr = np.zeros((n, n), dtype=int)

# Fill in the ones at the appropriate indices to make a '+'
mid = n // 2  # middle row and column
arr[mid, :] = 1  # fill in the middle row with 1's
arr[:, mid] = 1  # fill in the middle column with 1's

# Print the resulting array
print(arr)

Enter a positive odd integer greater than 2: 5
[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


### **2. Weight Loss**

**Description:** With your 25th birthday fast approaching, you decide to get in shape and lose some weight. You record your weight every day for five weeks starting on a Monday.

```
import numpy as np

weights = 175 - np.arange(5*7)/5
print(weights)
```

Given these daily weights, build an array with your average weight per weekend



In [3]:
# Write your code here

# Generate the daily weights for five weeks starting on a Monday
weights = 175 - np.arange(5*7)/5
weights = weights.reshape((5, 7))

# Calculate the average weight per weekend
weekend_avg = np.mean(weights[:, 5:], axis=1)

# Print the resulting array of average weight per weekend
print(weekend_avg)

[173.9 172.5 171.1 169.7 168.3]


### **3. Gaming Nicks**

**Description:** You want to start playing a first person shooter game and you are confused to find a gaming nick for yourself, hence you asked your friends and you’ve compiled the names into a Series called nicks.
import numpy as np
import pandas as pd



```
nicks = pd.Series([
    'Pik', 'Devine99', 'Spawn', 'Prodigy', 'Superkiller420', 'Pik', 'tornado',
    'tornado', 'roger', 'Gabriel', 'Chad', 'Ryan', 'Phoenix', 'Phoenix', 'Phoenix',
    'Phoenix', 'Zeltron', 'Ryan', 'Ruger', 'Ruger', 'roger',
    'roger', 'Chad', 'Chad', 'Gabriel'], dtype='string')
```

Determine how many people voted for the names ‘Phoenix’, ‘roger’, and ‘Pik’.


In [5]:
# Write your code here

# Define the nicks Series
nicks = pd.Series([
    'Pik', 'Devine99', 'Spawn', 'Prodigy', 'Superkiller420', 'Pik', 'tornado',
    'tornado', 'roger', 'Gabriel', 'Chad', 'Ryan', 'Phoenix', 'Phoenix', 'Phoenix',
    'Phoenix', 'Zeltron', 'Ryan', 'Ruger', 'Ruger', 'roger',
    'roger', 'Chad', 'Chad', 'Gabriel'], dtype='string')

# Count the number of votes for each name
counts = nicks.value_counts()

# Retrieve the count for each name we are interested in
phoenix_count = counts['Phoenix']
roger_count = counts['roger']
pik_count = counts['Pik']

# Print the counts for each name
print(f"Number of votes for Phoenix: {phoenix_count}")
print(f"Number of votes for roger: {roger_count}")
print(f"Number of votes for Pik: {pik_count}")

Number of votes for Phoenix: 4
Number of votes for roger: 3
Number of votes for Pik: 2
